---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: break-glass
rules:
- apiGroups: 
  - '*'
  resources:
  - '*'
  verbs:
  - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: break-glass-global
subjects:
- kind: Group
  name: breakglassgroupguid
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: break
  apiGroup: rbac.authorization.k8s.io